### ISSUE TITLE
Component does not trigger anything.

### ISSUE THREAD

**Issue by JordanchoEftimov** [healerlab/vue3-facebook-login#11]
Hello, i am trying to use the component this way, but it does not trigger anything in localhost.

```javascript
<HFaceBookLogin
      v-slot="fbLogin"
      app-id="407422541824896"
      @onSuccess="onSuccess"
      @onFailure="onFailure"
      scope="email,public_profile"
      fields="id,name,email,first_name,last_name,birthday"
    >
      <button
        @click="fbLogin.initFBLogin"
        type="button"
        class="w-100 mb-3 p-2 rounded rounded-3 border-1 text-start fb-button"
      >
        <img
          src="../../../assets/images/auth/register-view/facebook-icon.svg"
          alt="Social Media Icon"
          class="ps-4"
        />
        <span class="ps-5 fs-6">{{
          t("common.buttons.facebook-registration")
        }}</span>
      </button>
    </HFaceBookLogin>
```

**Comment by HealerNguyen** [comment]
Hi @JordanchoEftimov, Facebook login SDK cannot init on localhost or http, you can use ngrok to turn your localhost into https page and add your https url to fb login settings. Thanks

**Comment by ShaneChien1111** [comment]
Hi @HealerNguyen ,
I found the graph api version which calling from this library was hard code to v18.0, would it be better for the version also taking from the parameter passed in ??
![image](https://github.com/healerlab/vue3-facebook-login/assets/40823004/413c06d1-02f9-4cca-8841-e9d266fd55d0)

**Comment by HealerNguyen** [comment]
thank you for your report, I will fix soon. @ShaneChien1111

**Comment by HealerNguyen** [comment]
I have fixed and release new version that supports passing version dynamic.
