### ISSUE TITLE
Email scope not working

### ISSUE THREAD

**Issue by cvsouth** [healerlab/vue3-facebook-login#6]
Hi,

I like the package, thank you for creating and sharing it, however I am unable to get the email scope working. I have it enabled in the Facebook App and I'm passing the scope to the component attribute:

![image](https://github.com/healerlab/vue3-facebook-login/assets/11637621/3cb49675-f056-488b-b060-af3ff230b5ec)

![image](https://github.com/healerlab/vue3-facebook-login/assets/11637621/71cb57e3-215d-47cd-a7dd-4274d792860e)

This is the URL that the authentication popup has which does not request the email scope:

```https://www.facebook.com/privacy/consent/gdp/?params%5Bapp_id%5D=3732071110446454&params%5Bdisplay%5D=%22popup%22&params%5Bdomain%5D=%22localhost%22&params%5Bfallback_redirect_uri%5D=%22https%3A%5C%2F%5C%2Flocalhost%3A5173%5C%2Fsign-in%22&params%5Bkid_directed_site%5D=false&params%5Blogger_id%5D=%22f1235e7bcd2ccc%22&params%5Bnext%5D=%22read%22&params%5Bredirect_uri%5D=%22https%3A%5C%2F%5C%2Fstaticxx.facebook.com%5C%2Fx%5C%2Fconnect%5C%2Fxd_arbiter%5C%2F%3Fversion%3D46%23cb%3Df21cd6b1b78d094%26domain%3Dlocalhost%26is_canvas%3Dfalse%26origin%3Dhttps%5Cu00253A%5Cu00252F%5Cu00252Flocalhost%5Cu00253A5173%5Cu00252Ff38920341455a94%26relation%3Dopener%26frame%3Df3218752db83394%22&params%5Bresponse_type%5D=%22token%2Csigned_request%2Cgraph_domain%22&params%5Breturn_scopes%5D=false&params%5Bscope%5D=%5B%5D&params%5Bsdk%5D=%22joey%22&params%5Bsteps%5D=%7B%22read%22%3A%5B%22baseline%22%2C%22public_profile%22%2C%22email%22%5D%7D&params%5Btp%5D=%22unspecified%22&params%5Bcui_gk%5D=%22%5BPASS%5D%3Alogin_platformization_joey%2Clogin_platformization_read%22&source=gdp_delegated```

![image](https://github.com/healerlab/vue3-facebook-login/assets/11637621/a1eb364d-f914-4e34-9fc3-30beddb2a143)

If I edit the URL manually to add the email scope then it does work so it is definitely not an issue with how the Facebook app permissions are set up.

![image](https://github.com/healerlab/vue3-facebook-login/assets/11637621/fb7428a0-30bc-43c7-a917-7653d1f6ab78)

**Comment by cvsouth** [comment]
PR #7 fixes the scope request issue however the scope is `public_profile,email`. `id,name,email,first_name,last_name,birthday` are the fields to get from the graph api.

So I think either the scope and fields need passing to the component separately or for the component to only use the scope and not automatically request the user info via `getAuthInfo` before calling the callback, allowing the developer to call that method either in the callback itself or elsewhere, passing in the fields they want. I would go for the latter personally as that is more flexible. For example for my use case, I don't need that information at all, only the token.

**Comment by HealerNguyen** [comment]
Hello @cvsouth , thank you for your response, I will check your PR and response ASAP.

**Comment by HealerNguyen** [comment]
Hello @cvsouth , I have just updated and release new version for this component, I have added scope and fields, for more information you can check #8 . thank you so much

**Comment by cvsouth** [comment]
Thanks @HealerNguyen!
